name: CI-release-only

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release? yes/no'
        default: 'no'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: github.event.inputs.release == 'yes'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache Gradle
      uses: actions/cache@v2
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-${{ hashFiles('gradle') }}
    - name: Get publish token
      id: publish-token
      uses: atlassian-labs/artifact-publish-token@v1.0.1
    - name: Release
      env:
        atlassian_private_username: ${{ steps.publish-token.outputs.artifactoryUsername }}
        atlassian_private_password: ${{ steps.publish-token.outputs.artifactoryApiKey }}
      run: |
        ./gradlew build -x testIntegration
        ./gradlew release -Prelease.customUsername=${{ secrets.REPOSITORY_ACCESS_TOKEN }}
        ./gradlew publish
