name: CI-release-only

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release? yes/no'
        default: 'no'

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.inputs.release == 'yes'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache Gradle
      uses: actions/cache@v2
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-${{ hashFiles('gradle') }}
    - name: Release
      env:
        atlassian_private_username: ${{ secrets.ARTIFACTORY_USERNAME }}
        atlassian_private_password: ${{ secrets.ARTIFACTORY_API_KEY }}
      run: |
        ./gradlew build -x testIntegration
        ./gradlew release -Prelease.customUsername=${{ secrets.REPOSITORY_ACCESS_TOKEN }}
        ./gradlew publish
